import { toMinutes } from "./time";
import type { AcknowledgmentStatus, CrewTeam, Job, TeamMember } from "./types";

export const DEMO_DATE_LABEL = "Tuesday, September 22, 2026";

export const TEAM_MEMBERS: TeamMember[] = [
  { id: "tm-1", name: "Maria Lopez", role: "Crew lead", avatarColor: "#1e3a8a" },
  { id: "tm-2", name: "Ana Ruiz", role: "Cleaning technician", avatarColor: "#2563eb" },
  { id: "tm-3", name: "Sofia Martinez", role: "Crew lead", avatarColor: "#7c3aed" },
  { id: "tm-4", name: "Elena Cruz", role: "Cleaning technician", avatarColor: "#a855f7" },
  { id: "tm-5", name: "Daniela Garcia", role: "Crew lead", avatarColor: "#b91c1c" },
  { id: "tm-6", name: "Carla Torres", role: "Cleaning technician", avatarColor: "#dc2626" },
];

export const CREW_TEAMS: CrewTeam[] = [
  { id: "crew-1", name: "Crew 1", memberIds: ["tm-1", "tm-2"], vehicle: "Van 03", dispatcherName: "Jessica Miller" },
  { id: "crew-2", name: "Crew 2", memberIds: ["tm-3", "tm-4"], vehicle: "Van 07", dispatcherName: "Jessica Miller" },
  { id: "crew-3", name: "Crew 3", memberIds: ["tm-5", "tm-6"], vehicle: "Van 11", dispatcherName: "Jessica Miller" },
];

export const JOBS: Job[] = [
  {
    id: "1042",
    customerName: "Greenwood Residence",
    address: "214 Oak Street, Tampa, FL 33602",
    phone: "(813) 555-0142",
    contactName: "Dana Greenwood",
    serviceType: "Deep Cleaning",
    status: "confirmed",
    crewTeamId: "crew-1",
    scheduledStartMinutes: toMinutes(8, 15),
    scheduledEndMinutes: toMinutes(10, 15),
    durationMinutes: 120,
    accessNote: "Gate code available",
    accessCode: "4471",
    serviceInstructions: "Side gate entry. Dogs kept indoors during service. Start with upstairs bathrooms.",
  },
  {
    id: "1048",
    customerName: "Oakwood Dental",
    address: "829 Hillside Ave, Tampa, FL 33603",
    phone: "(813) 555-0198",
    contactName: "Front desk",
    serviceType: "Commercial Cleaning",
    status: "confirmed",
    crewTeamId: "crew-1",
    scheduledStartMinutes: toMinutes(10, 40),
    scheduledEndMinutes: toMinutes(12, 40),
    durationMinutes: 120,
    accessNote: "Front desk access",
    serviceInstructions: "Check in with front desk on arrival. Focus on waiting room and exam rooms 1–4.",
  },
  {
    id: "1055",
    customerName: "Riverside Apartment",
    address: "621 Riverside Dr, Tampa, FL 33604",
    phone: "(813) 555-0177",
    contactName: "Unit manager",
    serviceType: "Recurring Home Cleaning",
    status: "confirmed",
    crewTeamId: "crew-1",
    scheduledStartMinutes: toMinutes(13, 28),
    scheduledEndMinutes: toMinutes(15, 58),
    durationMinutes: 150,
    accessNote: "Call upon arrival",
    serviceInstructions: "Call the unit manager 10 minutes out. Standard recurring checklist.",
  },
  {
    id: "1061",
    customerName: "Harborview Offices",
    address: "145 Harborview Blvd, Tampa, FL 33605",
    phone: "(813) 555-0110",
    serviceType: "Commercial Cleaning",
    status: "confirmed",
    crewTeamId: "crew-2",
    scheduledStartMinutes: toMinutes(8, 15),
    scheduledEndMinutes: toMinutes(10, 45),
    durationMinutes: 150,
    accessNote: "Badge at security desk",
  },
  {
    id: "1093",
    customerName: "Maple Court",
    address: "88 Maple Court, Tampa, FL 33606",
    phone: "(813) 555-0134",
    serviceType: "Standard Cleaning",
    status: "confirmed",
    crewTeamId: "crew-2",
    scheduledStartMinutes: toMinutes(11, 15),
    scheduledEndMinutes: toMinutes(12, 30),
    durationMinutes: 75,
    accessNote: "Lockbox 7-7-2",
  },
  {
    id: "1067",
    customerName: "Summit Law Office",
    address: "500 Summit Ave, Tampa, FL 33607",
    phone: "(813) 555-0166",
    serviceType: "Commercial Cleaning",
    status: "confirmed",
    crewTeamId: "crew-2",
    scheduledStartMinutes: toMinutes(13, 0),
    scheduledEndMinutes: toMinutes(15, 0),
    durationMinutes: 120,
    accessNote: "Key at desk",
  },
  {
    id: "1075",
    customerName: "Lakeside Retail",
    address: "12 Lakeside Plaza, Tampa, FL 33608",
    phone: "(813) 555-0121",
    serviceType: "Commercial Cleaning",
    status: "confirmed",
    crewTeamId: "crew-3",
    scheduledStartMinutes: toMinutes(8, 10),
    scheduledEndMinutes: toMinutes(10, 40),
    durationMinutes: 150,
    accessNote: "Manager on site",
  },
  {
    id: "1081",
    jobberAppointmentId: "JB-4821",
    customerName: "Northgate Fitness Club",
    address: "2400 Northgate Pkwy, Bay 4, Tampa, FL 33609",
    phone: "(503) 555-0148",
    contactName: "R. Medina",
    serviceType: "Standard Cleaning",
    status: "conflict",
    crewTeamId: "crew-3",
    scheduledStartMinutes: toMinutes(11, 30),
    scheduledEndMinutes: toMinutes(13, 30),
    durationMinutes: 120,
    conflictNote: "Arrival 10 min late",
    travelInMinutes: 60,
    travelFromLabel: "Lakeside Retail",
    serviceInstructions: "Machine-scrub locker rooms, disinfect equipment, refill dispensers. Do not move free weights.",
  },
  {
    id: "1089",
    customerName: "Willow Creek Daycare",
    address: "76 Willow Creek Ln, Tampa, FL 33610",
    phone: "(813) 555-0155",
    serviceType: "Standard Cleaning",
    status: "confirmed",
    crewTeamId: "crew-3",
    scheduledStartMinutes: toMinutes(14, 20),
    scheduledEndMinutes: toMinutes(16, 20),
    durationMinutes: 120,
    accessNote: "Quiet hours until 2:30 PM",
  },
  {
    id: "1035",
    customerName: "Hilltop Residence",
    address: "92 Hilltop Rd, Tampa, FL 33611",
    phone: "(813) 555-0188",
    serviceType: "Deep Cleaning",
    status: "unassigned",
    crewTeamId: null,
    scheduledStartMinutes: null,
    scheduledEndMinutes: null,
    durationMinutes: 120,
    overdue: true,
    overdueSince: "Sep 21",
  },
  {
    id: "1101",
    customerName: "Bellmore Loft",
    address: "55 Bellmore St, Loft 2, Tampa, FL 33612",
    phone: "(813) 555-0199",
    serviceType: "Standard Cleaning",
    status: "unassigned",
    crewTeamId: null,
    scheduledStartMinutes: null,
    scheduledEndMinutes: null,
    durationMinutes: 90,
    clientWindowLabel: "1:00 – 4:00 PM",
    accessNote: "Lockbox 4-2-1",
    unassignedReason:
      "No crew can arrive within the client window — nearest availability is 4:15 PM. Reschedule in Jobber or add overtime.",
  },
];

export const DAY_NOTES: Record<string, string[]> = {
  "crew-1": ["Bring extra microfiber cloths for Oakwood Dental.", "Parking is available behind Riverside Apartment."],
  "crew-2": [
    "Harborview requires badge check-in at the security desk.",
    "Summit Law Office wants recycling bins emptied separately.",
  ],
  "crew-3": ["Northgate Fitness: do not move free weights.", "Willow Creek Daycare — quiet hours until 2:30 PM."],
};

export const ACKNOWLEDGMENTS: Record<string, Record<string, AcknowledgmentStatus>> = {
  "crew-1": { "tm-1": "pending", "tm-2": "sent-by-email" },
  "crew-2": { "tm-3": "acknowledged", "tm-4": "acknowledged" },
  "crew-3": { "tm-5": "sent-by-email", "tm-6": "pending" },
};
