import { addDays } from "date-fns";
import { toISO } from "./dates";
import type {
  AvailabilityEntry,
  CrewAssignment,
  Employee,
  Equipment,
  EquipmentAssignment,
  Project,
  RouteStop,
  RouteTypeDef,
  ServiceCategory,
} from "./types";

function rel(n: number): string {
  return toISO(addDays(new Date(), n));
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: "cat-roofing", name: "Roofing", color: "#f97316" },
  { id: "cat-electrical", name: "Electrical", color: "#eab308" },
  { id: "cat-plumbing", name: "Plumbing", color: "#3b82f6" },
  { id: "cat-hvac", name: "HVAC", color: "#06b6d4" },
  { id: "cat-painting", name: "Painting", color: "#ec4899" },
  { id: "cat-landscaping", name: "Landscaping", color: "#22c55e" },
  { id: "cat-general", name: "General Construction", color: "#64748b" },
];

function cat(id: string): ServiceCategory {
  return SERVICE_CATEGORIES.find((c) => c.id === id)!;
}

export const ROUTE_TYPES: RouteTypeDef[] = [
  { id: "rt-delivery", name: "Delivery", color: "#0ea5e9" },
  { id: "rt-service", name: "Service Call", color: "#8b5cf6" },
  { id: "rt-inspection", name: "Inspection", color: "#f59e0b" },
  { id: "rt-pickup", name: "Pickup", color: "#10b981" },
];

export const EQUIPMENT: Equipment[] = [
  { id: "eq-1", name: "Excavator CAT 305", type: "equipment" },
  { id: "eq-2", name: "Portable Generator 5kW", type: "equipment" },
  { id: "eq-3", name: "Scaffolding Set (20ft)", type: "equipment" },
  { id: "eq-4", name: "Air Compressor 185CFM", type: "equipment" },
  { id: "eq-5", name: "Concrete Mixer", type: "equipment" },
  { id: "veh-1", name: "Pickup Truck #12", type: "vehicle" },
  { id: "veh-2", name: "Box Truck #4", type: "vehicle" },
  { id: "veh-3", name: "Flatbed Trailer", type: "vehicle" },
  { id: "veh-4", name: "Bucket Truck #2", type: "vehicle" },
];

export const EMPLOYEES: Employee[] = [
  { id: "emp-1", name: "Ana Torres", avatarColor: "#2563eb" },
  { id: "emp-2", name: "Ben Whitfield", avatarColor: "#7c3aed", skills: ["Electrical License"] },
  { id: "emp-3", name: "Carla Nunez", avatarColor: "#db2777" },
  { id: "emp-4", name: "Diego Martinez", avatarColor: "#d97706" },
  { id: "emp-5", name: "Elena Popov", avatarColor: "#059669", skills: ["HVAC Certification"] },
  { id: "emp-6", name: "Frank Osei", avatarColor: "#0891b2" },
  { id: "emp-7", name: "Grace Lindqvist", avatarColor: "#4f46e5", skills: ["Confined Space Entry"] },
  { id: "emp-8", name: "Hector Alvarado", avatarColor: "#b91c1c" },
  { id: "emp-9", name: "Ivy Chen", avatarColor: "#0d9488" },
];

function addr(street: string, city: string, state: string, zip: string) {
  return { street, city, state, zip };
}

export const PROJECTS: Project[] = [
  // --- No date (schedulable, unscheduled) ---
  {
    id: "p-1",
    name: "Skyline Office Repaint",
    status: "Open",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("410 Skyline Ave", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-painting"),
  },
  {
    id: "p-2",
    name: "Maple Street Duplex Rewire",
    status: "Open",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("22 Maple St", "Brookfield", "IL", "60513"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-electrical"),
    priority: "High",
    requiredSkills: ["Electrical License"],
  },
  {
    id: "p-3",
    name: "Northgate Retail Buildout",
    status: "Approved",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("88 Northgate Plaza", "Millbrook", "OH", "44601"),
    hasSignedEstimate: false,
    serviceCategory: cat("cat-general"),
  },
  {
    id: "p-4",
    name: "Cedar Park HVAC Replacement",
    status: "Change of Order",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("77 Cedar Park Rd", "Cedar Park", "TX", "78613"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-hvac"),
  },
  {
    id: "p-16",
    name: "Crestview Electrical Panel Swap",
    status: "Open",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("14 Crestview Dr", "Ashford", "CT", "06278"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-electrical"),
  },
  {
    id: "p-19",
    name: "Timber Ridge Landscaping Design",
    status: "Open",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("5 Timber Ridge Ct", "Ashford", "CT", "06278"),
    hasSignedEstimate: false,
    serviceCategory: cat("cat-landscaping"),
  },

  // --- Overdue (Schedule) / dated in the past ---
  {
    id: "p-5",
    name: "Riverside Apartments Roof",
    status: "In Progress",
    beginDate: rel(-5),
    endDate: rel(-3),
    workDays: [rel(-5), rel(-4), rel(-3)],
    address: addr("900 Riverside Dr", "Millbrook", "OH", "44601"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-roofing"),
  },
  {
    id: "p-5a",
    parentProjectId: "p-5",
    name: "Riverside Apartments Roof — Gutter Section",
    status: "In Progress",
    beginDate: rel(-1),
    endDate: rel(-1),
    workDays: [rel(-1)],
    address: addr("900 Riverside Dr", "Millbrook", "OH", "44601"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-roofing"),
  },
  {
    id: "p-6",
    name: "Harbor View Plumbing Repair",
    status: "Scheduled",
    beginDate: rel(-2),
    endDate: rel(-2),
    workDays: [rel(-2)],
    address: addr("31 Harbor View Ln", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-plumbing"),
  },
  {
    id: "p-7",
    name: "Union Square Landscaping",
    status: "Open",
    beginDate: rel(-1),
    endDate: rel(-1),
    workDays: [],
    address: addr("6 Union Sq", "Brookfield", "IL", "60513"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-landscaping"),
  },
  {
    id: "p-8",
    name: "Grand Ave Facade Painting",
    status: "Change of Order",
    beginDate: rel(-6),
    endDate: rel(-4),
    workDays: [rel(-6), rel(-5), rel(-4)],
    address: addr("501 Grand Ave", "Millbrook", "OH", "44601"),
    hasSignedEstimate: false,
    serviceCategory: cat("cat-painting"),
  },
  {
    id: "p-17",
    name: "Bayside Warehouse Concrete",
    status: "Approved",
    beginDate: rel(-3),
    endDate: rel(-3),
    workDays: [rel(-3)],
    address: addr("2 Bayside Way", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-general"),
  },
  {
    id: "p-17a",
    parentProjectId: "p-17",
    name: "Bayside Warehouse Concrete — Loading Dock",
    status: "Approved",
    beginDate: rel(-3),
    endDate: rel(-3),
    workDays: [rel(-3)],
    address: addr("2 Bayside Way", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-general"),
  },

  // --- Scheduled, not overdue (spans today / future) ---
  {
    id: "p-9",
    name: "Lakeside Mall Electrical Upgrade",
    status: "Scheduled",
    beginDate: rel(0),
    endDate: rel(2),
    workDays: [rel(0), rel(1), rel(2)],
    address: addr("100 Lakeside Mall Rd", "Cedar Park", "TX", "78613"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-electrical"),
  },
  {
    id: "p-10",
    name: "Downtown Bridge Inspection Support",
    status: "In Progress",
    beginDate: rel(1),
    endDate: rel(1),
    workDays: [rel(1)],
    address: addr("1 Downtown Bridge Plz", "Ashford", "CT", "06278"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-general"),
    priority: "Low",
  },
  {
    id: "p-11",
    name: "Willow Creek HVAC Install",
    status: "Scheduled",
    beginDate: rel(2),
    endDate: rel(3),
    workDays: [rel(2), rel(3)],
    address: addr("48 Willow Creek Way", "Brookfield", "IL", "60513"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-hvac"),
  },
  {
    id: "p-11a",
    parentProjectId: "p-11",
    name: "Willow Creek HVAC Install — Rooftop Unit",
    status: "Scheduled",
    beginDate: rel(3),
    endDate: rel(3),
    workDays: [rel(3)],
    address: addr("48 Willow Creek Way", "Brookfield", "IL", "60513"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-hvac"),
  },
  {
    id: "p-12",
    name: "Sunset Plaza Roofing",
    status: "Open",
    beginDate: rel(4),
    endDate: rel(5),
    workDays: [rel(4), rel(5)],
    address: addr("77 Sunset Plaza", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-roofing"),
  },
  {
    id: "p-13",
    name: "Pine Hollow Landscaping Maintenance",
    status: "Scheduled",
    beginDate: rel(0),
    endDate: rel(1),
    workDays: [rel(0), rel(1)],
    address: addr("9 Pine Hollow Cir", "Millbrook", "OH", "44601"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-landscaping"),
  },
  {
    id: "p-14",
    name: "Ironwood Business Park Painting",
    status: "In Progress",
    beginDate: rel(-1),
    endDate: rel(1),
    workDays: [rel(-1), rel(0), rel(1)],
    address: addr("300 Ironwood Business Pkwy", "Cedar Park", "TX", "78613"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-painting"),
  },
  {
    id: "p-15",
    name: "Meadowbrook Plumbing Retrofit",
    status: "Change of Order",
    beginDate: rel(6),
    endDate: rel(6),
    workDays: [rel(6)],
    address: addr("15 Meadowbrook Ave", "Ashford", "CT", "06278"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-plumbing"),
  },
  {
    id: "p-18",
    name: "Foxglove Terrace HVAC Tune-up",
    status: "Scheduled",
    beginDate: rel(7),
    endDate: rel(7),
    workDays: [rel(7)],
    address: addr("61 Foxglove Terrace", "Brookfield", "IL", "60513"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-hvac"),
  },
  {
    id: "p-20",
    name: "Old Mill Roofing Emergency",
    status: "In Progress",
    beginDate: rel(0),
    endDate: rel(0),
    workDays: [rel(0)],
    address: addr("2 Old Mill Rd", "Fairview", "TX", "75001"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-roofing"),
    priority: "High",
  },
  {
    // Deliberately unassignable in the AI recommendation demo: no crew member
    // holds the "Crane Operator" skill it requires.
    id: "p-21",
    name: "Overpass Steel Beam Install",
    status: "Open",
    beginDate: null,
    endDate: null,
    workDays: [],
    address: addr("1 Overpass Way", "Ashford", "CT", "06278"),
    hasSignedEstimate: true,
    serviceCategory: cat("cat-general"),
    priority: "High",
    requiredSkills: ["Crane Operator"],
  },
];

export const CREW_ASSIGNMENTS: CrewAssignment[] = [
  { projectId: "p-5", employeeId: "emp-1", day: rel(-5) },
  { projectId: "p-5", employeeId: "emp-2", day: rel(-5) },
  { projectId: "p-5", employeeId: "emp-1", day: rel(-4) },
  { projectId: "p-6", employeeId: "emp-3", day: rel(-2) },
  { projectId: "p-8", employeeId: "emp-4", day: rel(-6) },
  { projectId: "p-9", employeeId: "emp-5", day: rel(0) },
  { projectId: "p-9", employeeId: "emp-6", day: rel(0) },
  { projectId: "p-9", employeeId: "emp-5", day: rel(1) },
  // Seeded conflict for the AI recommendation demo: Frank Osei is booked here but
  // has a Sick day off on the same date (see av-2) — the recommendation should
  // detect and resolve this by reassigning to an available crew member.
  { projectId: "p-10", employeeId: "emp-6", day: rel(1) },
  { projectId: "p-11", employeeId: "emp-8", day: rel(2) },
  { projectId: "p-11a", employeeId: "emp-8", day: rel(3) },
  { projectId: "p-13", employeeId: "emp-9", day: rel(0) },
  { projectId: "p-13", employeeId: "emp-3", day: rel(0) },
  { projectId: "p-14", employeeId: "emp-2", day: rel(0) },
  { projectId: "p-20", employeeId: "emp-1", day: rel(0) },
];

export const EQUIPMENT_ASSIGNMENTS: EquipmentAssignment[] = [
  { id: "ea-1", equipmentId: "veh-1", scope: "project", projectId: "p-9", day: rel(0) },
  { id: "ea-2", equipmentId: "eq-1", scope: "member-day", projectId: "p-5", employeeId: "emp-1", day: rel(-5) },
  { id: "ea-3", equipmentId: "veh-2", scope: "member-whole-project", projectId: "p-11", employeeId: "emp-8" },
  { id: "ea-4", equipmentId: "eq-3", scope: "project", projectId: "p-8", day: rel(-6) },
];

export const ROUTE_STOPS: RouteStop[] = [
  { id: "rs-1", employeeId: "emp-5", projectId: "p-9", day: rel(0), stopNumber: 1, routeTypeId: "rt-service", routeStatus: "Completed" },
  { id: "rs-2", employeeId: "emp-5", projectId: "p-13", day: rel(0), stopNumber: 2, routeTypeId: "rt-inspection", routeStatus: "In Progress" },
  { id: "rs-3", employeeId: "emp-1", projectId: "p-20", day: rel(0), stopNumber: 1, routeTypeId: "rt-service", routeStatus: "Pending" },
  { id: "rs-4", employeeId: "emp-7", projectId: "p-10", day: rel(1), stopNumber: 1, routeTypeId: "rt-inspection", routeStatus: "Pending" },
  { id: "rs-5", employeeId: "emp-8", projectId: "p-11", day: rel(2), stopNumber: 1, routeTypeId: "rt-delivery", routeStatus: "Pending" },
  { id: "rs-6", employeeId: "emp-3", projectId: "p-6", day: rel(-2), stopNumber: 1, routeTypeId: "rt-service", routeStatus: "Completed" },
  { id: "rs-7", employeeId: "emp-3", projectId: "p-13", day: rel(0), stopNumber: 1, routeTypeId: "rt-pickup", routeStatus: "In Progress" },
  { id: "rs-8", employeeId: "emp-2", projectId: "p-14", day: rel(0), stopNumber: 1, routeTypeId: "rt-service", routeStatus: "Pending" },
];

export const AVAILABILITY_ENTRIES: AvailabilityEntry[] = [
  {
    id: "av-1",
    employeeId: "emp-4",
    category: "dayoff",
    type: "Vacation",
    reason: "",
    startDate: rel(0),
    endDate: rel(2),
    isPTO: true,
  },
  {
    id: "av-2",
    employeeId: "emp-6",
    category: "dayoff",
    type: "Sick",
    reason: "",
    startDate: rel(1),
    endDate: rel(1),
    isPTO: false,
  },
  {
    id: "av-3",
    employeeId: "emp-9",
    category: "activity",
    type: "Training",
    reason: "Forklift certification renewal",
    startDate: rel(2),
    endDate: rel(2),
    isPTO: false,
  },
  {
    id: "av-4",
    employeeId: "emp-7",
    category: "activity",
    type: "Meeting",
    reason: "Quarterly safety review",
    startDate: rel(-1),
    endDate: rel(-1),
    isPTO: false,
  },
];
